version: 2
jobs:
  jdk8:
    working_directory: ~/apollo
    docker:
      - image: maven:3.5.4-jdk-8
    steps:
      - checkout
      - restore_cache:
          key: v1-deps-{{ checksum "pom.xml" }}
      - run:
          command: mvn -Pcoverage -Pmissinglink --fail-never dependency:go-offline clean compile || true
          environment:
            MAVEN_OPTS: -Xmx512m
      - save_cache:
          key: v1-deps-{{ checksum "pom.xml" }}
          paths:
            - ~/.m2
      - run:
          command: mvn -Pcoverage -Pmissinglink verify
          environment:
            MAVEN_OPTS: -Xmx512m
      - run:
          name: Save test results
          command: |
            mkdir -p ~/junit/
            find . -type f -regex ".*/target/surefire-reports/.*xml" -exec cp {} ~/junit/ \;
          when: always
      - store_test_results:
          path: ~/junit
      - store_artifacts:
          path: ~/junit
      - run: bash <(curl -s https://codecov.io/bash)
  jdk10:
    working_directory: ~/apollo
    docker:
      - image: maven:3.5.4-jdk-10-slim
    steps:
      - checkout
      - restore_cache:
          key: v1-deps-jdk10-{{ checksum "pom.xml" }}
      - run: mvn dependency:go-offline clean compile || true
      - save_cache:
          key: v1-deps-jdk10-{{ checksum "pom.xml" }}
          paths:
            - ~/.m2
      - run:
          command: mvn verify
          environment:
            MAVEN_OPTS: -Xmx512m --add-modules java.xml.bind

workflows:
  version: 2
  build:
    jobs:
      - jdk8
      - jdk10